postgresql install test

diff --git a/.github/workflows/create-netbox01-vm.yml b/.github/workflows/create-netbox01-vm.yml
--- a/.github/workflows/create-netbox01-vm.yml
+++ b/.github/workflows/create-netbox01-vm.yml
@@ -132,7 +132,8 @@ jobs:
           token: ${{ secrets.REPO_SECRETS_PAT }}
 
   setup-vm:
-    if: ${{ !failure() && !cancelled() }}
+    # if: ${{ !failure() && !cancelled() }}
+    if: false
     needs: [create-vm-from-template]
     runs-on: [self-hosted, linux, initial, rexonix-infra]
     steps:
@@ -156,7 +157,7 @@ jobs:
 
   postgresql-installation:
     if: ${{ !failure() && !cancelled() }}
-    needs: [setup-vm]
+    #needs: [setup-vm]
     runs-on: [self-hosted, linux, initial, rexonix-infra]
     steps:
         - uses: Anush008/clean-after-action@v4.2.0
@@ -168,8 +169,10 @@ jobs:
             username: ${{ secrets.VM_USERNAME }}
             key: ${{ secrets.RUNNER01_SSH_PRIVATE_KEY }}
             script: |
-              sudo apt update
-              sudo apt install -y postgresql postgresql-contrib
+              if ! systemctl is-active --quiet postgresql; then
+                sudo apt update
+                sudo apt install -y postgresql postgresql-contrib
+              fi
               psql -V
         
         - name: Create DB in PostgreSQL
@@ -179,16 +182,14 @@ jobs:
             username: ${{ secrets.VM_USERNAME }}
             key: ${{ secrets.RUNNER01_SSH_PRIVATE_KEY }}
             script: |
-              sudo -u postgres psql -c "
-              CREATE DATABASE netbox;
-              CREATE USER netbox WITH PASSWORD '${{ secrets.VM_PASSWORD }}';
-              ALTER DATABASE netbox OWNER TO netbox;
-              GRANT CREATE ON SCHEMA public TO netbox;
-              \q"
+              set -e
+              sudo -u postgres psql -v ON_ERROR_STOP=1 -c "CREATE USER netbox WITH PASSWORD '${{ secrets.VM_PASSWORD }}';" || true
+              sudo -u postgres psql -v ON_ERROR_STOP=1 -c "CREATE DATABASE netbox OWNER netbox;" || true
+              sudo -u postgres psql -v ON_ERROR_STOP=1 -d netbox -c "GRANT CREATE ON SCHEMA public TO netbox;"
 
   redis-installation:
     if: ${{ !failure() && !cancelled() }}
-    needs: [setup-vm]
+    #needs: [setup-vm]
     runs-on: [self-hosted, linux, initial, rexonix-infra]
     steps:
         - uses: Anush008/clean-after-action@v4.2.0
@@ -200,8 +201,10 @@ jobs:
             username: ${{ secrets.VM_USERNAME }}
             key: ${{ secrets.RUNNER01_SSH_PRIVATE_KEY }}
             script: |
-              sudo apt update
-              sudo apt install -y redis-server
+              if ! systemctl is-active --quiet redis; then
+                sudo apt update
+                sudo apt install -y redis-server
+              fi
               redis-server -v
               redis-cli ping
 
